#! /bin/sh
# /etc/init.d/smart_home


### EGIN INIT INFO

# Provides :		smart_home

# Required-Start: 	$remote_fs $syslog

# Required-Stop: 	$remote_fs $syslog

# Default-Start:	2 3 4 5

# Default-Stop: 	0 1 6

# Short-Description:	smart_home

# Description: 		smart_home

### END INIT INFO


case "$1" in
  start)
     echo "Starting skrypt"
     sudo python /usr/local/sbin/smart_home.py &
     ;;
  stop)
     echo "Stopping skrypt"
     killall python
     ;;
   *)
     echo "Usage: /etc/init.d/smart_home{start|stop}"
     exit 1
     ;;

esac


exit 0
  	
